Repository hapipal/toys, pull requests merged in 2023-02, with the labels that each got.

#33 feat: add local typings
  lib/index.d.ts
  package.json
Labels: enhancement, breaking changes, types

#35 Support node v16+, hapi v20+
  .travis.yml
  API.md
  LICENSE
  README.md
  package.json
  test/esm.js
Labels: breaking changes, test, dependency

#36 Remove reacher(), transformer(), event(), and stream() methods
  API.md
  README.md
  lib/index.js
  test/esm.js
  test/index.js
Labels: breaking changes
